const menu=document.querySelector('.menu-toggle'),nav=document.querySelector('#navigation');
function closeMenu(){menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','Open menu');nav.classList.remove('open')}
menu.addEventListener('click',()=>{const open=menu.getAttribute('aria-expanded')!=='true';menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'Close menu':'Open menu');nav.classList.toggle('open',open)});
nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeMenu));document.addEventListener('keydown',e=>{if(e.key==='Escape')closeMenu()});window.addEventListener('resize',()=>{if(window.innerWidth>800)closeMenu()});
const gallery=document.querySelector('#gallery');document.querySelector('#gallery-prev').addEventListener('click',()=>gallery.scrollBy({left:-gallery.clientWidth*.8,behavior:'smooth'}));document.querySelector('#gallery-next').addEventListener('click',()=>gallery.scrollBy({left:gallery.clientWidth*.8,behavior:'smooth'}));
const dialog=document.querySelector('#detail-dialog'),content=document.querySelector('#dialog-content');document.querySelector('.dialog-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)dialog.close()}});dialog.addEventListener('close',()=>{document.body.style.overflow=''});
function openDialog(){document.body.style.overflow='hidden';dialog.showModal()}
const details={scan:{title:'A little more intelligence.',label:'NINJASCAN / ECOSYSTEM TOOL',copy:'NinjaScan presents an interface for exploring token contracts, liquidity, holders and market activity, with Ethereum and Robinhood network selections. Open the original project tool to check its current functionality.',note:'This preview links to the existing service. Analysis is not a guarantee of token safety.',url:'https://www.realninjacat.com/#ninjascan',action:'Explore NinjaScan'},swap:{title:'One simpler way to swap.',label:'NINJASWAP / COMING SOON',copy:'The project proposes a swap experience designed to make accessing the Robinhood ecosystem easier, with cross-chain routing and integrated bridging. The original website labels NinjaSwap as coming soon.',note:'A product vision, not a functioning swap on this preview.',url:'https://www.realninjacat.com/#msft-stock-rewards',action:'Explore the project ecosystem'},rewards:{title:'Understand the rewards.',label:'MSFT / HOLDER INITIATIVE',copy:'The project describes an MSFT-linked holder rewards dashboard and automated distribution concept. Eligibility, the precise asset delivered, supported locations and terms should be checked directly with the project.',note:'No rewards, returns or Microsoft partnership are guaranteed or verified by this design preview.',url:'https://rewards.realninjacat.com/',action:'View the rewards dashboard'}};
document.querySelectorAll('[data-detail]').forEach(b=>b.addEventListener('click',()=>{const d=details[b.dataset.detail];dialog.classList.remove('art-dialog');content.innerHTML=`<div class="eyebrow">${d.label}</div><h2>${d.title}</h2><p>${d.copy}</p><p>${d.note}</p><a class="button button-dark" href="${d.url}" target="_blank" rel="noopener">${d.action} <span>↗</span></a>`;openDialog()}));
const cats=[{id:1,name:'The Original Spirit',color:'Gold & black',description:'A moonlit village. Golden armour. The unmistakable Ninjacat spirit.'},{id:0,name:'The Sakura Spirit',color:'White & red',description:'Cherry blossoms, a white kimono and the quiet confidence of a little ninja.'},{id:3,name:'The Cedar Spirit',color:'Red & black',description:'A lantern-lit adventure with a Lebanese flag headband and a fearless heart.'},{id:4,name:'The Moonlight Spirit',color:'Violet',description:'Violet armour and cherry blossoms under a luminous moon.'},{id:5,name:'The Bamboo Spirit',color:'Forest green',description:'Green bamboo, flowing waterfalls and an adventurous forest ninja.'},{id:2,name:'The Brave Spirit',color:'Red, white & blue',description:'A bold, flag-inspired character with a shield and a heroic stance.'}];let selectedCat=0;
function renderCat(index){selectedCat=(index+cats.length)%cats.length;const c=cats[selectedCat];content.innerHTML=`<img src="assets/cat-${c.id}.webp" alt="${c.name} — ${c.color}" width="1254" height="1254"><h2>${c.name}</h2><p>${c.description}</p><div class="art-nav"><button id="art-prev" aria-label="Previous artwork">← Previous</button><button id="art-next" aria-label="Next artwork">Next →</button></div>`;document.querySelector('#art-prev').addEventListener('click',()=>renderCat(selectedCat-1));document.querySelector('#art-next').addEventListener('click',()=>renderCat(selectedCat+1))}
document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>{dialog.classList.add('art-dialog');renderCat(cats.findIndex(c=>c.id===Number(b.dataset.cat)));openDialog()}));document.addEventListener('keydown',e=>{if(dialog.open&&dialog.classList.contains('art-dialog')){if(e.key==='ArrowRight')renderCat(selectedCat+1);if(e.key==='ArrowLeft')renderCat(selectedCat-1)}});
let toastTimeout;function toast(message){const t=document.querySelector('#toast');t.textContent=message;t.classList.add('show');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>t.classList.remove('show'),3000)}
document.querySelector('#copy-contract').addEventListener('click',async()=>{const value='0x4A88cf518EA6B7D1184184D6eab78dF7252a74F1';try{await navigator.clipboard.writeText(value);toast('Token contract copied')}catch{dialog.classList.remove('art-dialog');content.innerHTML='<div class="eyebrow">TOKEN CONTRACT</div><h2>Copy the address</h2><p style="overflow-wrap:anywhere;user-select:all">'+value+'</p>';openDialog()}});
